// this file was autogenerated by tailwind-to-dart
// see https://github.com/joshmossas/tailwind-to-dart for details
import "dart:ui";

class Colors {
  Colors();
  static const transparent = Color.fromARGB(0, 0, 0, 0);

  /// #000
  static const black = Color(0xFF000);

  /// #fff
  static const white = Color(0xFFFFF);
  static _ColorsSlate get slate => _ColorsSlate();
  static _ColorsGray get gray => _ColorsGray();
  static _ColorsZinc get zinc => _ColorsZinc();
  static _ColorsNeutral get neutral => _ColorsNeutral();
  static _ColorsStone get stone => _ColorsStone();
  static _ColorsRed get red => _ColorsRed();
  static _ColorsOrange get orange => _ColorsOrange();
  static _ColorsAmber get amber => _ColorsAmber();
  static _ColorsYellow get yellow => _ColorsYellow();
  static _ColorsLime get lime => _ColorsLime();
  static _ColorsGreen get green => _ColorsGreen();
  static _ColorsEmerald get emerald => _ColorsEmerald();
  static _ColorsTeal get teal => _ColorsTeal();
  static _ColorsCyan get cyan => _ColorsCyan();
  static _ColorsSky get sky => _ColorsSky();
  static _ColorsBlue get blue => _ColorsBlue();
  static _ColorsIndigo get indigo => _ColorsIndigo();
  static _ColorsViolet get violet => _ColorsViolet();
  static _ColorsPurple get purple => _ColorsPurple();
  static _ColorsFuchsia get fuchsia => _ColorsFuchsia();
  static _ColorsPink get pink => _ColorsPink();
  static _ColorsRose get rose => _ColorsRose();

  /// #123456
  static const myCustomColor = Color(0xFF123456);
}

class _ColorsSlate {
  _ColorsSlate();

  /// #f8fafc
  final shade50 = Color(0xFFF8FAFC);

  /// #f1f5f9
  final shade100 = Color(0xFFF1F5F9);

  /// #e2e8f0
  final shade200 = Color(0xFFE2E8F0);

  /// #cbd5e1
  final shade300 = Color(0xFFCBD5E1);

  /// #94a3b8
  final shade400 = Color(0xFF94A3B8);

  /// #64748b
  final shade500 = Color(0xFF64748B);

  /// #475569
  final shade600 = Color(0xFF475569);

  /// #334155
  final shade700 = Color(0xFF334155);

  /// #1e293b
  final shade800 = Color(0xFF1E293B);

  /// #0f172a
  final shade900 = Color(0xFF0F172A);

  /// #020617
  final shade950 = Color(0xFF020617);
}

class _ColorsGray {
  _ColorsGray();

  /// #f9fafb
  final shade50 = Color(0xFFF9FAFB);

  /// #f3f4f6
  final shade100 = Color(0xFFF3F4F6);

  /// #e5e7eb
  final shade200 = Color(0xFFE5E7EB);

  /// #d1d5db
  final shade300 = Color(0xFFD1D5DB);

  /// #9ca3af
  final shade400 = Color(0xFF9CA3AF);

  /// #6b7280
  final shade500 = Color(0xFF6B7280);

  /// #4b5563
  final shade600 = Color(0xFF4B5563);

  /// #374151
  final shade700 = Color(0xFF374151);

  /// #1f2937
  final shade800 = Color(0xFF1F2937);

  /// #111827
  final shade900 = Color(0xFF111827);

  /// #030712
  final shade950 = Color(0xFF030712);
}

class _ColorsZinc {
  _ColorsZinc();

  /// #fafafa
  final shade50 = Color(0xFFFAFAFA);

  /// #f4f4f5
  final shade100 = Color(0xFFF4F4F5);

  /// #e4e4e7
  final shade200 = Color(0xFFE4E4E7);

  /// #d4d4d8
  final shade300 = Color(0xFFD4D4D8);

  /// #a1a1aa
  final shade400 = Color(0xFFA1A1AA);

  /// #71717a
  final shade500 = Color(0xFF71717A);

  /// #52525b
  final shade600 = Color(0xFF52525B);

  /// #3f3f46
  final shade700 = Color(0xFF3F3F46);

  /// #27272a
  final shade800 = Color(0xFF27272A);

  /// #18181b
  final shade900 = Color(0xFF18181B);

  /// #09090b
  final shade950 = Color(0xFF09090B);
}

class _ColorsNeutral {
  _ColorsNeutral();

  /// #fafafa
  final shade50 = Color(0xFFFAFAFA);

  /// #f5f5f5
  final shade100 = Color(0xFFF5F5F5);

  /// #e5e5e5
  final shade200 = Color(0xFFE5E5E5);

  /// #d4d4d4
  final shade300 = Color(0xFFD4D4D4);

  /// #a3a3a3
  final shade400 = Color(0xFFA3A3A3);

  /// #737373
  final shade500 = Color(0xFF737373);

  /// #525252
  final shade600 = Color(0xFF525252);

  /// #404040
  final shade700 = Color(0xFF404040);

  /// #262626
  final shade800 = Color(0xFF262626);

  /// #171717
  final shade900 = Color(0xFF171717);

  /// #0a0a0a
  final shade950 = Color(0xFF0A0A0A);
}

class _ColorsStone {
  _ColorsStone();

  /// #fafaf9
  final shade50 = Color(0xFFFAFAF9);

  /// #f5f5f4
  final shade100 = Color(0xFFF5F5F4);

  /// #e7e5e4
  final shade200 = Color(0xFFE7E5E4);

  /// #d6d3d1
  final shade300 = Color(0xFFD6D3D1);

  /// #a8a29e
  final shade400 = Color(0xFFA8A29E);

  /// #78716c
  final shade500 = Color(0xFF78716C);

  /// #57534e
  final shade600 = Color(0xFF57534E);

  /// #44403c
  final shade700 = Color(0xFF44403C);

  /// #292524
  final shade800 = Color(0xFF292524);

  /// #1c1917
  final shade900 = Color(0xFF1C1917);

  /// #0c0a09
  final shade950 = Color(0xFF0C0A09);
}

class _ColorsRed {
  _ColorsRed();

  /// #fef2f2
  final shade50 = Color(0xFFFEF2F2);

  /// #fee2e2
  final shade100 = Color(0xFFFEE2E2);

  /// #fecaca
  final shade200 = Color(0xFFFECACA);

  /// #fca5a5
  final shade300 = Color(0xFFFCA5A5);

  /// #f87171
  final shade400 = Color(0xFFF87171);

  /// #ef4444
  final shade500 = Color(0xFFEF4444);

  /// #dc2626
  final shade600 = Color(0xFFDC2626);

  /// #b91c1c
  final shade700 = Color(0xFFB91C1C);

  /// #991b1b
  final shade800 = Color(0xFF991B1B);

  /// #7f1d1d
  final shade900 = Color(0xFF7F1D1D);

  /// #450a0a
  final shade950 = Color(0xFF450A0A);
}

class _ColorsOrange {
  _ColorsOrange();

  /// #fff7ed
  final shade50 = Color(0xFFFFF7ED);

  /// #ffedd5
  final shade100 = Color(0xFFFFEDD5);

  /// #fed7aa
  final shade200 = Color(0xFFFED7AA);

  /// #fdba74
  final shade300 = Color(0xFFFDBA74);

  /// #fb923c
  final shade400 = Color(0xFFFB923C);

  /// #f97316
  final shade500 = Color(0xFFF97316);

  /// #ea580c
  final shade600 = Color(0xFFEA580C);

  /// #c2410c
  final shade700 = Color(0xFFC2410C);

  /// #9a3412
  final shade800 = Color(0xFF9A3412);

  /// #7c2d12
  final shade900 = Color(0xFF7C2D12);

  /// #431407
  final shade950 = Color(0xFF431407);
}

class _ColorsAmber {
  _ColorsAmber();

  /// #fffbeb
  final shade50 = Color(0xFFFFFBEB);

  /// #fef3c7
  final shade100 = Color(0xFFFEF3C7);

  /// #fde68a
  final shade200 = Color(0xFFFDE68A);

  /// #fcd34d
  final shade300 = Color(0xFFFCD34D);

  /// #fbbf24
  final shade400 = Color(0xFFFBBF24);

  /// #f59e0b
  final shade500 = Color(0xFFF59E0B);

  /// #d97706
  final shade600 = Color(0xFFD97706);

  /// #b45309
  final shade700 = Color(0xFFB45309);

  /// #92400e
  final shade800 = Color(0xFF92400E);

  /// #78350f
  final shade900 = Color(0xFF78350F);

  /// #451a03
  final shade950 = Color(0xFF451A03);
}

class _ColorsYellow {
  _ColorsYellow();

  /// #fefce8
  final shade50 = Color(0xFFFEFCE8);

  /// #fef9c3
  final shade100 = Color(0xFFFEF9C3);

  /// #fef08a
  final shade200 = Color(0xFFFEF08A);

  /// #fde047
  final shade300 = Color(0xFFFDE047);

  /// #facc15
  final shade400 = Color(0xFFFACC15);

  /// #eab308
  final shade500 = Color(0xFFEAB308);

  /// #ca8a04
  final shade600 = Color(0xFFCA8A04);

  /// #a16207
  final shade700 = Color(0xFFA16207);

  /// #854d0e
  final shade800 = Color(0xFF854D0E);

  /// #713f12
  final shade900 = Color(0xFF713F12);

  /// #422006
  final shade950 = Color(0xFF422006);
}

class _ColorsLime {
  _ColorsLime();

  /// #f7fee7
  final shade50 = Color(0xFFF7FEE7);

  /// #ecfccb
  final shade100 = Color(0xFFECFCCB);

  /// #d9f99d
  final shade200 = Color(0xFFD9F99D);

  /// #bef264
  final shade300 = Color(0xFFBEF264);

  /// #a3e635
  final shade400 = Color(0xFFA3E635);

  /// #84cc16
  final shade500 = Color(0xFF84CC16);

  /// #65a30d
  final shade600 = Color(0xFF65A30D);

  /// #4d7c0f
  final shade700 = Color(0xFF4D7C0F);

  /// #3f6212
  final shade800 = Color(0xFF3F6212);

  /// #365314
  final shade900 = Color(0xFF365314);

  /// #1a2e05
  final shade950 = Color(0xFF1A2E05);
}

class _ColorsGreen {
  _ColorsGreen();

  /// #f0fdf4
  final shade50 = Color(0xFFF0FDF4);

  /// #dcfce7
  final shade100 = Color(0xFFDCFCE7);

  /// #bbf7d0
  final shade200 = Color(0xFFBBF7D0);

  /// #86efac
  final shade300 = Color(0xFF86EFAC);

  /// #4ade80
  final shade400 = Color(0xFF4ADE80);

  /// #22c55e
  final shade500 = Color(0xFF22C55E);

  /// #16a34a
  final shade600 = Color(0xFF16A34A);

  /// #15803d
  final shade700 = Color(0xFF15803D);

  /// #166534
  final shade800 = Color(0xFF166534);

  /// #14532d
  final shade900 = Color(0xFF14532D);

  /// #052e16
  final shade950 = Color(0xFF052E16);
}

class _ColorsEmerald {
  _ColorsEmerald();

  /// #ecfdf5
  final shade50 = Color(0xFFECFDF5);

  /// #d1fae5
  final shade100 = Color(0xFFD1FAE5);

  /// #a7f3d0
  final shade200 = Color(0xFFA7F3D0);

  /// #6ee7b7
  final shade300 = Color(0xFF6EE7B7);

  /// #34d399
  final shade400 = Color(0xFF34D399);

  /// #10b981
  final shade500 = Color(0xFF10B981);

  /// #059669
  final shade600 = Color(0xFF059669);

  /// #047857
  final shade700 = Color(0xFF047857);

  /// #065f46
  final shade800 = Color(0xFF065F46);

  /// #064e3b
  final shade900 = Color(0xFF064E3B);

  /// #022c22
  final shade950 = Color(0xFF022C22);
}

class _ColorsTeal {
  _ColorsTeal();

  /// #f0fdfa
  final shade50 = Color(0xFFF0FDFA);

  /// #ccfbf1
  final shade100 = Color(0xFFCCFBF1);

  /// #99f6e4
  final shade200 = Color(0xFF99F6E4);

  /// #5eead4
  final shade300 = Color(0xFF5EEAD4);

  /// #2dd4bf
  final shade400 = Color(0xFF2DD4BF);

  /// #14b8a6
  final shade500 = Color(0xFF14B8A6);

  /// #0d9488
  final shade600 = Color(0xFF0D9488);

  /// #0f766e
  final shade700 = Color(0xFF0F766E);

  /// #115e59
  final shade800 = Color(0xFF115E59);

  /// #134e4a
  final shade900 = Color(0xFF134E4A);

  /// #042f2e
  final shade950 = Color(0xFF042F2E);
}

class _ColorsCyan {
  _ColorsCyan();

  /// #ecfeff
  final shade50 = Color(0xFFECFEFF);

  /// #cffafe
  final shade100 = Color(0xFFCFFAFE);

  /// #a5f3fc
  final shade200 = Color(0xFFA5F3FC);

  /// #67e8f9
  final shade300 = Color(0xFF67E8F9);

  /// #22d3ee
  final shade400 = Color(0xFF22D3EE);

  /// #06b6d4
  final shade500 = Color(0xFF06B6D4);

  /// #0891b2
  final shade600 = Color(0xFF0891B2);

  /// #0e7490
  final shade700 = Color(0xFF0E7490);

  /// #155e75
  final shade800 = Color(0xFF155E75);

  /// #164e63
  final shade900 = Color(0xFF164E63);

  /// #083344
  final shade950 = Color(0xFF083344);
}

class _ColorsSky {
  _ColorsSky();

  /// #f0f9ff
  final shade50 = Color(0xFFF0F9FF);

  /// #e0f2fe
  final shade100 = Color(0xFFE0F2FE);

  /// #bae6fd
  final shade200 = Color(0xFFBAE6FD);

  /// #7dd3fc
  final shade300 = Color(0xFF7DD3FC);

  /// #38bdf8
  final shade400 = Color(0xFF38BDF8);

  /// #0ea5e9
  final shade500 = Color(0xFF0EA5E9);

  /// #0284c7
  final shade600 = Color(0xFF0284C7);

  /// #0369a1
  final shade700 = Color(0xFF0369A1);

  /// #075985
  final shade800 = Color(0xFF075985);

  /// #0c4a6e
  final shade900 = Color(0xFF0C4A6E);

  /// #082f49
  final shade950 = Color(0xFF082F49);
}

class _ColorsBlue {
  _ColorsBlue();

  /// #eff6ff
  final shade50 = Color(0xFFEFF6FF);

  /// #dbeafe
  final shade100 = Color(0xFFDBEAFE);

  /// #bfdbfe
  final shade200 = Color(0xFFBFDBFE);

  /// #93c5fd
  final shade300 = Color(0xFF93C5FD);

  /// #60a5fa
  final shade400 = Color(0xFF60A5FA);

  /// #3b82f6
  final shade500 = Color(0xFF3B82F6);

  /// #2563eb
  final shade600 = Color(0xFF2563EB);

  /// #1d4ed8
  final shade700 = Color(0xFF1D4ED8);

  /// #1e40af
  final shade800 = Color(0xFF1E40AF);

  /// #1e3a8a
  final shade900 = Color(0xFF1E3A8A);

  /// #172554
  final shade950 = Color(0xFF172554);
}

class _ColorsIndigo {
  _ColorsIndigo();

  /// #eef2ff
  final shade50 = Color(0xFFEEF2FF);

  /// #e0e7ff
  final shade100 = Color(0xFFE0E7FF);

  /// #c7d2fe
  final shade200 = Color(0xFFC7D2FE);

  /// #a5b4fc
  final shade300 = Color(0xFFA5B4FC);

  /// #818cf8
  final shade400 = Color(0xFF818CF8);

  /// #6366f1
  final shade500 = Color(0xFF6366F1);

  /// #4f46e5
  final shade600 = Color(0xFF4F46E5);

  /// #4338ca
  final shade700 = Color(0xFF4338CA);

  /// #3730a3
  final shade800 = Color(0xFF3730A3);

  /// #312e81
  final shade900 = Color(0xFF312E81);

  /// #1e1b4b
  final shade950 = Color(0xFF1E1B4B);
}

class _ColorsViolet {
  _ColorsViolet();

  /// #f5f3ff
  final shade50 = Color(0xFFF5F3FF);

  /// #ede9fe
  final shade100 = Color(0xFFEDE9FE);

  /// #ddd6fe
  final shade200 = Color(0xFFDDD6FE);

  /// #c4b5fd
  final shade300 = Color(0xFFC4B5FD);

  /// #a78bfa
  final shade400 = Color(0xFFA78BFA);

  /// #8b5cf6
  final shade500 = Color(0xFF8B5CF6);

  /// #7c3aed
  final shade600 = Color(0xFF7C3AED);

  /// #6d28d9
  final shade700 = Color(0xFF6D28D9);

  /// #5b21b6
  final shade800 = Color(0xFF5B21B6);

  /// #4c1d95
  final shade900 = Color(0xFF4C1D95);

  /// #2e1065
  final shade950 = Color(0xFF2E1065);
}

class _ColorsPurple {
  _ColorsPurple();

  /// #faf5ff
  final shade50 = Color(0xFFFAF5FF);

  /// #f3e8ff
  final shade100 = Color(0xFFF3E8FF);

  /// #e9d5ff
  final shade200 = Color(0xFFE9D5FF);

  /// #d8b4fe
  final shade300 = Color(0xFFD8B4FE);

  /// #c084fc
  final shade400 = Color(0xFFC084FC);

  /// #a855f7
  final shade500 = Color(0xFFA855F7);

  /// #9333ea
  final shade600 = Color(0xFF9333EA);

  /// #7e22ce
  final shade700 = Color(0xFF7E22CE);

  /// #6b21a8
  final shade800 = Color(0xFF6B21A8);

  /// #581c87
  final shade900 = Color(0xFF581C87);

  /// #3b0764
  final shade950 = Color(0xFF3B0764);
}

class _ColorsFuchsia {
  _ColorsFuchsia();

  /// #fdf4ff
  final shade50 = Color(0xFFFDF4FF);

  /// #fae8ff
  final shade100 = Color(0xFFFAE8FF);

  /// #f5d0fe
  final shade200 = Color(0xFFF5D0FE);

  /// #f0abfc
  final shade300 = Color(0xFFF0ABFC);

  /// #e879f9
  final shade400 = Color(0xFFE879F9);

  /// #d946ef
  final shade500 = Color(0xFFD946EF);

  /// #c026d3
  final shade600 = Color(0xFFC026D3);

  /// #a21caf
  final shade700 = Color(0xFFA21CAF);

  /// #86198f
  final shade800 = Color(0xFF86198F);

  /// #701a75
  final shade900 = Color(0xFF701A75);

  /// #4a044e
  final shade950 = Color(0xFF4A044E);
}

class _ColorsPink {
  _ColorsPink();

  /// #fdf2f8
  final shade50 = Color(0xFFFDF2F8);

  /// #fce7f3
  final shade100 = Color(0xFFFCE7F3);

  /// #fbcfe8
  final shade200 = Color(0xFFFBCFE8);

  /// #f9a8d4
  final shade300 = Color(0xFFF9A8D4);

  /// #f472b6
  final shade400 = Color(0xFFF472B6);

  /// #ec4899
  final shade500 = Color(0xFFEC4899);

  /// #db2777
  final shade600 = Color(0xFFDB2777);

  /// #be185d
  final shade700 = Color(0xFFBE185D);

  /// #9d174d
  final shade800 = Color(0xFF9D174D);

  /// #831843
  final shade900 = Color(0xFF831843);

  /// #500724
  final shade950 = Color(0xFF500724);
}

class _ColorsRose {
  _ColorsRose();

  /// #fff1f2
  final shade50 = Color(0xFFFFF1F2);

  /// #ffe4e6
  final shade100 = Color(0xFFFFE4E6);

  /// #fecdd3
  final shade200 = Color(0xFFFECDD3);

  /// #fda4af
  final shade300 = Color(0xFFFDA4AF);

  /// #fb7185
  final shade400 = Color(0xFFFB7185);

  /// #f43f5e
  final shade500 = Color(0xFFF43F5E);

  /// #e11d48
  final shade600 = Color(0xFFE11D48);

  /// #be123c
  final shade700 = Color(0xFFBE123C);

  /// #9f1239
  final shade800 = Color(0xFF9F1239);

  /// #881337
  final shade900 = Color(0xFF881337);

  /// #4c0519
  final shade950 = Color(0xFF4C0519);
}

class FontSizes {
  FontSizes();
  static _FontSizesXs get xs => _FontSizesXs();
  static _FontSizesSm get sm => _FontSizesSm();
  static _FontSizesBase get base => _FontSizesBase();
  static _FontSizesLg get lg => _FontSizesLg();
  static _FontSizesXl get xl => _FontSizesXl();
  static _FontSizes2xl get size2xl => _FontSizes2xl();
  static _FontSizes3xl get size3xl => _FontSizes3xl();
  static _FontSizes4xl get size4xl => _FontSizes4xl();
  static _FontSizes5xl get size5xl => _FontSizes5xl();
  static _FontSizes6xl get size6xl => _FontSizes6xl();
  static _FontSizes7xl get size7xl => _FontSizes7xl();
  static _FontSizes8xl get size8xl => _FontSizes8xl();
  static _FontSizes9xl get size9xl => _FontSizes9xl();
}

class _FontSizesXs {
  _FontSizesXs();

  /// fontSize: 12px
  final double size0 = 12;
  _FontSizesXs1 get size1 => _FontSizesXs1();
}

class _FontSizesXs1 {
  _FontSizesXs1();

  /// fontSize: 16px
  final double lineHeight = 16;
}

class _FontSizesSm {
  _FontSizesSm();

  /// fontSize: 14px
  final double size0 = 14;
  _FontSizesSm1 get size1 => _FontSizesSm1();
}

class _FontSizesSm1 {
  _FontSizesSm1();

  /// fontSize: 20px
  final double lineHeight = 20;
}

class _FontSizesBase {
  _FontSizesBase();

  /// fontSize: 16px
  final double size0 = 16;
  _FontSizesBase1 get size1 => _FontSizesBase1();
}

class _FontSizesBase1 {
  _FontSizesBase1();

  /// fontSize: 24px
  final double lineHeight = 24;
}

class _FontSizesLg {
  _FontSizesLg();

  /// fontSize: 18px
  final double size0 = 18;
  _FontSizesLg1 get size1 => _FontSizesLg1();
}

class _FontSizesLg1 {
  _FontSizesLg1();

  /// fontSize: 28px
  final double lineHeight = 28;
}

class _FontSizesXl {
  _FontSizesXl();

  /// fontSize: 20px
  final double size0 = 20;
  _FontSizesXl1 get size1 => _FontSizesXl1();
}

class _FontSizesXl1 {
  _FontSizesXl1();

  /// fontSize: 28px
  final double lineHeight = 28;
}

class _FontSizes2xl {
  _FontSizes2xl();

  /// fontSize: 24px
  final double size0 = 24;
  _FontSizes2xl1 get size1 => _FontSizes2xl1();
}

class _FontSizes2xl1 {
  _FontSizes2xl1();

  /// fontSize: 32px
  final double lineHeight = 32;
}

class _FontSizes3xl {
  _FontSizes3xl();

  /// fontSize: 30px
  final double size0 = 30;
  _FontSizes3xl1 get size1 => _FontSizes3xl1();
}

class _FontSizes3xl1 {
  _FontSizes3xl1();

  /// fontSize: 36px
  final double lineHeight = 36;
}

class _FontSizes4xl {
  _FontSizes4xl();

  /// fontSize: 36px
  final double size0 = 36;
  _FontSizes4xl1 get size1 => _FontSizes4xl1();
}

class _FontSizes4xl1 {
  _FontSizes4xl1();

  /// fontSize: 40px
  final double lineHeight = 40;
}

class _FontSizes5xl {
  _FontSizes5xl();

  /// fontSize: 48px
  final double size0 = 48;
  _FontSizes5xl1 get size1 => _FontSizes5xl1();
}

class _FontSizes5xl1 {
  _FontSizes5xl1();

  /// fontSize: 0px
  final double lineHeight = 0;
}

class _FontSizes6xl {
  _FontSizes6xl();

  /// fontSize: 60px
  final double size0 = 60;
  _FontSizes6xl1 get size1 => _FontSizes6xl1();
}

class _FontSizes6xl1 {
  _FontSizes6xl1();

  /// fontSize: 0px
  final double lineHeight = 0;
}

class _FontSizes7xl {
  _FontSizes7xl();

  /// fontSize: 72px
  final double size0 = 72;
  _FontSizes7xl1 get size1 => _FontSizes7xl1();
}

class _FontSizes7xl1 {
  _FontSizes7xl1();

  /// fontSize: 0px
  final double lineHeight = 0;
}

class _FontSizes8xl {
  _FontSizes8xl();

  /// fontSize: 96px
  final double size0 = 96;
  _FontSizes8xl1 get size1 => _FontSizes8xl1();
}

class _FontSizes8xl1 {
  _FontSizes8xl1();

  /// fontSize: 0px
  final double lineHeight = 0;
}

class _FontSizes9xl {
  _FontSizes9xl();

  /// fontSize: 128px
  final double size0 = 128;
  _FontSizes9xl1 get size1 => _FontSizes9xl1();
}

class _FontSizes9xl1 {
  _FontSizes9xl1();

  /// fontSize: 0px
  final double lineHeight = 0;
}

class Space {
  Space();

  /// size: 0px
  static const double size0 = 0;

  /// size: 4px
  static const double size1 = 4;

  /// size: 8px
  static const double size2 = 8;

  /// size: 12px
  static const double size3 = 12;

  /// size: 16px
  static const double size4 = 16;

  /// size: 20px
  static const double size5 = 20;

  /// size: 24px
  static const double size6 = 24;

  /// size: 28px
  static const double size7 = 28;

  /// size: 32px
  static const double size8 = 32;

  /// size: 36px
  static const double size9 = 36;

  /// size: 40px
  static const double size10 = 40;

  /// size: 44px
  static const double size11 = 44;

  /// size: 48px
  static const double size12 = 48;

  /// size: 56px
  static const double size14 = 56;

  /// size: 64px
  static const double size16 = 64;

  /// size: 80px
  static const double size20 = 80;

  /// size: 96px
  static const double size24 = 96;

  /// size: 112px
  static const double size28 = 112;

  /// size: 128px
  static const double size32 = 128;

  /// size: 144px
  static const double size36 = 144;

  /// size: 160px
  static const double size40 = 160;

  /// size: 176px
  static const double size44 = 176;

  /// size: 192px
  static const double size48 = 192;

  /// size: 208px
  static const double size52 = 208;

  /// size: 224px
  static const double size56 = 224;

  /// size: 240px
  static const double size60 = 240;

  /// size: 256px
  static const double size64 = 256;

  /// size: 288px
  static const double size72 = 288;

  /// size: 320px
  static const double size80 = 320;

  /// size: 384px
  static const double size96 = 384;

  /// size: 1px
  static const double px = 1;

  /// size: 2px
  static const double size0Point5 = 2;

  /// size: 6px
  static const double size1Point5 = 6;

  /// size: 10px
  static const double size2Point5 = 10;

  /// size: 14px
  static const double size3Point5 = 14;
}
