// this file was autogenerated by tailwind-to-dart
// see https://github.com/joshmossas/tailwind-to-dart for details
import "dart:ui";

class Colors {
  const Colors();
  static const transparent = Color.fromARGB(0, 0, 0, 0);

  /// #000
  static const black = Color(0xFF000);

  /// #fff
  static const white = Color(0xFFFFF);
  static const slate = _ColorsSlate();
  static const gray = _ColorsGray();
  static const zinc = _ColorsZinc();
  static const neutral = _ColorsNeutral();
  static const stone = _ColorsStone();
  static const red = _ColorsRed();
  static const orange = _ColorsOrange();
  static const amber = _ColorsAmber();
  static const yellow = _ColorsYellow();
  static const lime = _ColorsLime();
  static const green = _ColorsGreen();
  static const emerald = _ColorsEmerald();
  static const teal = _ColorsTeal();
  static const cyan = _ColorsCyan();
  static const sky = _ColorsSky();
  static const blue = _ColorsBlue();
  static const indigo = _ColorsIndigo();
  static const violet = _ColorsViolet();
  static const purple = _ColorsPurple();
  static const fuchsia = _ColorsFuchsia();
  static const pink = _ColorsPink();
  static const rose = _ColorsRose();

  /// #123456
  static const myCustomColor = Color(0xFF123456);

  /// rgb(1, 2, 3)
  static const myCustomRgbColor = Color.fromRGBO(1, 2, 3, 1);

  /// rgba(1, 2, 3, 0.5)
  static const myCustomRgbaColor = Color.fromRGBO(1, 2, 3, 0.5);
}

class _ColorsSlate {
  const _ColorsSlate();

  /// #f8fafc
  final shade50 = const Color(0xFFF8FAFC);

  /// #f1f5f9
  final shade100 = const Color(0xFFF1F5F9);

  /// #e2e8f0
  final shade200 = const Color(0xFFE2E8F0);

  /// #cbd5e1
  final shade300 = const Color(0xFFCBD5E1);

  /// #94a3b8
  final shade400 = const Color(0xFF94A3B8);

  /// #64748b
  final shade500 = const Color(0xFF64748B);

  /// #475569
  final shade600 = const Color(0xFF475569);

  /// #334155
  final shade700 = const Color(0xFF334155);

  /// #1e293b
  final shade800 = const Color(0xFF1E293B);

  /// #0f172a
  final shade900 = const Color(0xFF0F172A);

  /// #020617
  final shade950 = const Color(0xFF020617);
}

class _ColorsGray {
  const _ColorsGray();

  /// #f9fafb
  final shade50 = const Color(0xFFF9FAFB);

  /// #f3f4f6
  final shade100 = const Color(0xFFF3F4F6);

  /// #e5e7eb
  final shade200 = const Color(0xFFE5E7EB);

  /// #d1d5db
  final shade300 = const Color(0xFFD1D5DB);

  /// #9ca3af
  final shade400 = const Color(0xFF9CA3AF);

  /// #6b7280
  final shade500 = const Color(0xFF6B7280);

  /// #4b5563
  final shade600 = const Color(0xFF4B5563);

  /// #374151
  final shade700 = const Color(0xFF374151);

  /// #1f2937
  final shade800 = const Color(0xFF1F2937);

  /// #111827
  final shade900 = const Color(0xFF111827);

  /// #030712
  final shade950 = const Color(0xFF030712);
}

class _ColorsZinc {
  const _ColorsZinc();

  /// #fafafa
  final shade50 = const Color(0xFFFAFAFA);

  /// #f4f4f5
  final shade100 = const Color(0xFFF4F4F5);

  /// #e4e4e7
  final shade200 = const Color(0xFFE4E4E7);

  /// #d4d4d8
  final shade300 = const Color(0xFFD4D4D8);

  /// #a1a1aa
  final shade400 = const Color(0xFFA1A1AA);

  /// #71717a
  final shade500 = const Color(0xFF71717A);

  /// #52525b
  final shade600 = const Color(0xFF52525B);

  /// #3f3f46
  final shade700 = const Color(0xFF3F3F46);

  /// #27272a
  final shade800 = const Color(0xFF27272A);

  /// #18181b
  final shade900 = const Color(0xFF18181B);

  /// #09090b
  final shade950 = const Color(0xFF09090B);
}

class _ColorsNeutral {
  const _ColorsNeutral();

  /// #fafafa
  final shade50 = const Color(0xFFFAFAFA);

  /// #f5f5f5
  final shade100 = const Color(0xFFF5F5F5);

  /// #e5e5e5
  final shade200 = const Color(0xFFE5E5E5);

  /// #d4d4d4
  final shade300 = const Color(0xFFD4D4D4);

  /// #a3a3a3
  final shade400 = const Color(0xFFA3A3A3);

  /// #737373
  final shade500 = const Color(0xFF737373);

  /// #525252
  final shade600 = const Color(0xFF525252);

  /// #404040
  final shade700 = const Color(0xFF404040);

  /// #262626
  final shade800 = const Color(0xFF262626);

  /// #171717
  final shade900 = const Color(0xFF171717);

  /// #0a0a0a
  final shade950 = const Color(0xFF0A0A0A);
}

class _ColorsStone {
  const _ColorsStone();

  /// #fafaf9
  final shade50 = const Color(0xFFFAFAF9);

  /// #f5f5f4
  final shade100 = const Color(0xFFF5F5F4);

  /// #e7e5e4
  final shade200 = const Color(0xFFE7E5E4);

  /// #d6d3d1
  final shade300 = const Color(0xFFD6D3D1);

  /// #a8a29e
  final shade400 = const Color(0xFFA8A29E);

  /// #78716c
  final shade500 = const Color(0xFF78716C);

  /// #57534e
  final shade600 = const Color(0xFF57534E);

  /// #44403c
  final shade700 = const Color(0xFF44403C);

  /// #292524
  final shade800 = const Color(0xFF292524);

  /// #1c1917
  final shade900 = const Color(0xFF1C1917);

  /// #0c0a09
  final shade950 = const Color(0xFF0C0A09);
}

class _ColorsRed {
  const _ColorsRed();

  /// #fef2f2
  final shade50 = const Color(0xFFFEF2F2);

  /// #fee2e2
  final shade100 = const Color(0xFFFEE2E2);

  /// #fecaca
  final shade200 = const Color(0xFFFECACA);

  /// #fca5a5
  final shade300 = const Color(0xFFFCA5A5);

  /// #f87171
  final shade400 = const Color(0xFFF87171);

  /// #ef4444
  final shade500 = const Color(0xFFEF4444);

  /// #dc2626
  final shade600 = const Color(0xFFDC2626);

  /// #b91c1c
  final shade700 = const Color(0xFFB91C1C);

  /// #991b1b
  final shade800 = const Color(0xFF991B1B);

  /// #7f1d1d
  final shade900 = const Color(0xFF7F1D1D);

  /// #450a0a
  final shade950 = const Color(0xFF450A0A);
}

class _ColorsOrange {
  const _ColorsOrange();

  /// #fff7ed
  final shade50 = const Color(0xFFFFF7ED);

  /// #ffedd5
  final shade100 = const Color(0xFFFFEDD5);

  /// #fed7aa
  final shade200 = const Color(0xFFFED7AA);

  /// #fdba74
  final shade300 = const Color(0xFFFDBA74);

  /// #fb923c
  final shade400 = const Color(0xFFFB923C);

  /// #f97316
  final shade500 = const Color(0xFFF97316);

  /// #ea580c
  final shade600 = const Color(0xFFEA580C);

  /// #c2410c
  final shade700 = const Color(0xFFC2410C);

  /// #9a3412
  final shade800 = const Color(0xFF9A3412);

  /// #7c2d12
  final shade900 = const Color(0xFF7C2D12);

  /// #431407
  final shade950 = const Color(0xFF431407);
}

class _ColorsAmber {
  const _ColorsAmber();

  /// #fffbeb
  final shade50 = const Color(0xFFFFFBEB);

  /// #fef3c7
  final shade100 = const Color(0xFFFEF3C7);

  /// #fde68a
  final shade200 = const Color(0xFFFDE68A);

  /// #fcd34d
  final shade300 = const Color(0xFFFCD34D);

  /// #fbbf24
  final shade400 = const Color(0xFFFBBF24);

  /// #f59e0b
  final shade500 = const Color(0xFFF59E0B);

  /// #d97706
  final shade600 = const Color(0xFFD97706);

  /// #b45309
  final shade700 = const Color(0xFFB45309);

  /// #92400e
  final shade800 = const Color(0xFF92400E);

  /// #78350f
  final shade900 = const Color(0xFF78350F);

  /// #451a03
  final shade950 = const Color(0xFF451A03);
}

class _ColorsYellow {
  const _ColorsYellow();

  /// #fefce8
  final shade50 = const Color(0xFFFEFCE8);

  /// #fef9c3
  final shade100 = const Color(0xFFFEF9C3);

  /// #fef08a
  final shade200 = const Color(0xFFFEF08A);

  /// #fde047
  final shade300 = const Color(0xFFFDE047);

  /// #facc15
  final shade400 = const Color(0xFFFACC15);

  /// #eab308
  final shade500 = const Color(0xFFEAB308);

  /// #ca8a04
  final shade600 = const Color(0xFFCA8A04);

  /// #a16207
  final shade700 = const Color(0xFFA16207);

  /// #854d0e
  final shade800 = const Color(0xFF854D0E);

  /// #713f12
  final shade900 = const Color(0xFF713F12);

  /// #422006
  final shade950 = const Color(0xFF422006);
}

class _ColorsLime {
  const _ColorsLime();

  /// #f7fee7
  final shade50 = const Color(0xFFF7FEE7);

  /// #ecfccb
  final shade100 = const Color(0xFFECFCCB);

  /// #d9f99d
  final shade200 = const Color(0xFFD9F99D);

  /// #bef264
  final shade300 = const Color(0xFFBEF264);

  /// #a3e635
  final shade400 = const Color(0xFFA3E635);

  /// #84cc16
  final shade500 = const Color(0xFF84CC16);

  /// #65a30d
  final shade600 = const Color(0xFF65A30D);

  /// #4d7c0f
  final shade700 = const Color(0xFF4D7C0F);

  /// #3f6212
  final shade800 = const Color(0xFF3F6212);

  /// #365314
  final shade900 = const Color(0xFF365314);

  /// #1a2e05
  final shade950 = const Color(0xFF1A2E05);
}

class _ColorsGreen {
  const _ColorsGreen();

  /// #f0fdf4
  final shade50 = const Color(0xFFF0FDF4);

  /// #dcfce7
  final shade100 = const Color(0xFFDCFCE7);

  /// #bbf7d0
  final shade200 = const Color(0xFFBBF7D0);

  /// #86efac
  final shade300 = const Color(0xFF86EFAC);

  /// #4ade80
  final shade400 = const Color(0xFF4ADE80);

  /// #22c55e
  final shade500 = const Color(0xFF22C55E);

  /// #16a34a
  final shade600 = const Color(0xFF16A34A);

  /// #15803d
  final shade700 = const Color(0xFF15803D);

  /// #166534
  final shade800 = const Color(0xFF166534);

  /// #14532d
  final shade900 = const Color(0xFF14532D);

  /// #052e16
  final shade950 = const Color(0xFF052E16);
}

class _ColorsEmerald {
  const _ColorsEmerald();

  /// #ecfdf5
  final shade50 = const Color(0xFFECFDF5);

  /// #d1fae5
  final shade100 = const Color(0xFFD1FAE5);

  /// #a7f3d0
  final shade200 = const Color(0xFFA7F3D0);

  /// #6ee7b7
  final shade300 = const Color(0xFF6EE7B7);

  /// #34d399
  final shade400 = const Color(0xFF34D399);

  /// #10b981
  final shade500 = const Color(0xFF10B981);

  /// #059669
  final shade600 = const Color(0xFF059669);

  /// #047857
  final shade700 = const Color(0xFF047857);

  /// #065f46
  final shade800 = const Color(0xFF065F46);

  /// #064e3b
  final shade900 = const Color(0xFF064E3B);

  /// #022c22
  final shade950 = const Color(0xFF022C22);
}

class _ColorsTeal {
  const _ColorsTeal();

  /// #f0fdfa
  final shade50 = const Color(0xFFF0FDFA);

  /// #ccfbf1
  final shade100 = const Color(0xFFCCFBF1);

  /// #99f6e4
  final shade200 = const Color(0xFF99F6E4);

  /// #5eead4
  final shade300 = const Color(0xFF5EEAD4);

  /// #2dd4bf
  final shade400 = const Color(0xFF2DD4BF);

  /// #14b8a6
  final shade500 = const Color(0xFF14B8A6);

  /// #0d9488
  final shade600 = const Color(0xFF0D9488);

  /// #0f766e
  final shade700 = const Color(0xFF0F766E);

  /// #115e59
  final shade800 = const Color(0xFF115E59);

  /// #134e4a
  final shade900 = const Color(0xFF134E4A);

  /// #042f2e
  final shade950 = const Color(0xFF042F2E);
}

class _ColorsCyan {
  const _ColorsCyan();

  /// #ecfeff
  final shade50 = const Color(0xFFECFEFF);

  /// #cffafe
  final shade100 = const Color(0xFFCFFAFE);

  /// #a5f3fc
  final shade200 = const Color(0xFFA5F3FC);

  /// #67e8f9
  final shade300 = const Color(0xFF67E8F9);

  /// #22d3ee
  final shade400 = const Color(0xFF22D3EE);

  /// #06b6d4
  final shade500 = const Color(0xFF06B6D4);

  /// #0891b2
  final shade600 = const Color(0xFF0891B2);

  /// #0e7490
  final shade700 = const Color(0xFF0E7490);

  /// #155e75
  final shade800 = const Color(0xFF155E75);

  /// #164e63
  final shade900 = const Color(0xFF164E63);

  /// #083344
  final shade950 = const Color(0xFF083344);
}

class _ColorsSky {
  const _ColorsSky();

  /// #f0f9ff
  final shade50 = const Color(0xFFF0F9FF);

  /// #e0f2fe
  final shade100 = const Color(0xFFE0F2FE);

  /// #bae6fd
  final shade200 = const Color(0xFFBAE6FD);

  /// #7dd3fc
  final shade300 = const Color(0xFF7DD3FC);

  /// #38bdf8
  final shade400 = const Color(0xFF38BDF8);

  /// #0ea5e9
  final shade500 = const Color(0xFF0EA5E9);

  /// #0284c7
  final shade600 = const Color(0xFF0284C7);

  /// #0369a1
  final shade700 = const Color(0xFF0369A1);

  /// #075985
  final shade800 = const Color(0xFF075985);

  /// #0c4a6e
  final shade900 = const Color(0xFF0C4A6E);

  /// #082f49
  final shade950 = const Color(0xFF082F49);
}

class _ColorsBlue {
  const _ColorsBlue();

  /// #eff6ff
  final shade50 = const Color(0xFFEFF6FF);

  /// #dbeafe
  final shade100 = const Color(0xFFDBEAFE);

  /// #bfdbfe
  final shade200 = const Color(0xFFBFDBFE);

  /// #93c5fd
  final shade300 = const Color(0xFF93C5FD);

  /// #60a5fa
  final shade400 = const Color(0xFF60A5FA);

  /// #3b82f6
  final shade500 = const Color(0xFF3B82F6);

  /// #2563eb
  final shade600 = const Color(0xFF2563EB);

  /// #1d4ed8
  final shade700 = const Color(0xFF1D4ED8);

  /// #1e40af
  final shade800 = const Color(0xFF1E40AF);

  /// #1e3a8a
  final shade900 = const Color(0xFF1E3A8A);

  /// #172554
  final shade950 = const Color(0xFF172554);
}

class _ColorsIndigo {
  const _ColorsIndigo();

  /// #eef2ff
  final shade50 = const Color(0xFFEEF2FF);

  /// #e0e7ff
  final shade100 = const Color(0xFFE0E7FF);

  /// #c7d2fe
  final shade200 = const Color(0xFFC7D2FE);

  /// #a5b4fc
  final shade300 = const Color(0xFFA5B4FC);

  /// #818cf8
  final shade400 = const Color(0xFF818CF8);

  /// #6366f1
  final shade500 = const Color(0xFF6366F1);

  /// #4f46e5
  final shade600 = const Color(0xFF4F46E5);

  /// #4338ca
  final shade700 = const Color(0xFF4338CA);

  /// #3730a3
  final shade800 = const Color(0xFF3730A3);

  /// #312e81
  final shade900 = const Color(0xFF312E81);

  /// #1e1b4b
  final shade950 = const Color(0xFF1E1B4B);
}

class _ColorsViolet {
  const _ColorsViolet();

  /// #f5f3ff
  final shade50 = const Color(0xFFF5F3FF);

  /// #ede9fe
  final shade100 = const Color(0xFFEDE9FE);

  /// #ddd6fe
  final shade200 = const Color(0xFFDDD6FE);

  /// #c4b5fd
  final shade300 = const Color(0xFFC4B5FD);

  /// #a78bfa
  final shade400 = const Color(0xFFA78BFA);

  /// #8b5cf6
  final shade500 = const Color(0xFF8B5CF6);

  /// #7c3aed
  final shade600 = const Color(0xFF7C3AED);

  /// #6d28d9
  final shade700 = const Color(0xFF6D28D9);

  /// #5b21b6
  final shade800 = const Color(0xFF5B21B6);

  /// #4c1d95
  final shade900 = const Color(0xFF4C1D95);

  /// #2e1065
  final shade950 = const Color(0xFF2E1065);
}

class _ColorsPurple {
  const _ColorsPurple();

  /// #faf5ff
  final shade50 = const Color(0xFFFAF5FF);

  /// #f3e8ff
  final shade100 = const Color(0xFFF3E8FF);

  /// #e9d5ff
  final shade200 = const Color(0xFFE9D5FF);

  /// #d8b4fe
  final shade300 = const Color(0xFFD8B4FE);

  /// #c084fc
  final shade400 = const Color(0xFFC084FC);

  /// #a855f7
  final shade500 = const Color(0xFFA855F7);

  /// #9333ea
  final shade600 = const Color(0xFF9333EA);

  /// #7e22ce
  final shade700 = const Color(0xFF7E22CE);

  /// #6b21a8
  final shade800 = const Color(0xFF6B21A8);

  /// #581c87
  final shade900 = const Color(0xFF581C87);

  /// #3b0764
  final shade950 = const Color(0xFF3B0764);
}

class _ColorsFuchsia {
  const _ColorsFuchsia();

  /// #fdf4ff
  final shade50 = const Color(0xFFFDF4FF);

  /// #fae8ff
  final shade100 = const Color(0xFFFAE8FF);

  /// #f5d0fe
  final shade200 = const Color(0xFFF5D0FE);

  /// #f0abfc
  final shade300 = const Color(0xFFF0ABFC);

  /// #e879f9
  final shade400 = const Color(0xFFE879F9);

  /// #d946ef
  final shade500 = const Color(0xFFD946EF);

  /// #c026d3
  final shade600 = const Color(0xFFC026D3);

  /// #a21caf
  final shade700 = const Color(0xFFA21CAF);

  /// #86198f
  final shade800 = const Color(0xFF86198F);

  /// #701a75
  final shade900 = const Color(0xFF701A75);

  /// #4a044e
  final shade950 = const Color(0xFF4A044E);
}

class _ColorsPink {
  const _ColorsPink();

  /// #fdf2f8
  final shade50 = const Color(0xFFFDF2F8);

  /// #fce7f3
  final shade100 = const Color(0xFFFCE7F3);

  /// #fbcfe8
  final shade200 = const Color(0xFFFBCFE8);

  /// #f9a8d4
  final shade300 = const Color(0xFFF9A8D4);

  /// #f472b6
  final shade400 = const Color(0xFFF472B6);

  /// #ec4899
  final shade500 = const Color(0xFFEC4899);

  /// #db2777
  final shade600 = const Color(0xFFDB2777);

  /// #be185d
  final shade700 = const Color(0xFFBE185D);

  /// #9d174d
  final shade800 = const Color(0xFF9D174D);

  /// #831843
  final shade900 = const Color(0xFF831843);

  /// #500724
  final shade950 = const Color(0xFF500724);
}

class _ColorsRose {
  const _ColorsRose();

  /// #fff1f2
  final shade50 = const Color(0xFFFFF1F2);

  /// #ffe4e6
  final shade100 = const Color(0xFFFFE4E6);

  /// #fecdd3
  final shade200 = const Color(0xFFFECDD3);

  /// #fda4af
  final shade300 = const Color(0xFFFDA4AF);

  /// #fb7185
  final shade400 = const Color(0xFFFB7185);

  /// #f43f5e
  final shade500 = const Color(0xFFF43F5E);

  /// #e11d48
  final shade600 = const Color(0xFFE11D48);

  /// #be123c
  final shade700 = const Color(0xFFBE123C);

  /// #9f1239
  final shade800 = const Color(0xFF9F1239);

  /// #881337
  final shade900 = const Color(0xFF881337);

  /// #4c0519
  final shade950 = const Color(0xFF4C0519);
}

class FontSizes {
  const FontSizes();

  /// fontSize: 12px
  static const double xs = 12;

  /// fontSize: 14px
  static const double sm = 14;

  /// fontSize: 16px
  static const double base = 16;

  /// fontSize: 18px
  static const double lg = 18;

  /// fontSize: 20px
  static const double xl = 20;

  /// fontSize: 24px
  static const double size2xl = 24;

  /// fontSize: 30px
  static const double size3xl = 30;

  /// fontSize: 36px
  static const double size4xl = 36;

  /// fontSize: 48px
  static const double size5xl = 48;

  /// fontSize: 60px
  static const double size6xl = 60;

  /// fontSize: 72px
  static const double size7xl = 72;

  /// fontSize: 96px
  static const double size8xl = 96;

  /// fontSize: 128px
  static const double size9xl = 128;
}

class Spacing {
  const Spacing();

  /// spacing: 0
  static const double size0 = 0;

  /// spacing: 4
  static const double size1 = 4;

  /// spacing: 8
  static const double size2 = 8;

  /// spacing: 12
  static const double size3 = 12;

  /// spacing: 16
  static const double size4 = 16;

  /// spacing: 20
  static const double size5 = 20;

  /// spacing: 24
  static const double size6 = 24;

  /// spacing: 28
  static const double size7 = 28;

  /// spacing: 32
  static const double size8 = 32;

  /// spacing: 36
  static const double size9 = 36;

  /// spacing: 40
  static const double size10 = 40;

  /// spacing: 44
  static const double size11 = 44;

  /// spacing: 48
  static const double size12 = 48;

  /// spacing: 56
  static const double size14 = 56;

  /// spacing: 64
  static const double size16 = 64;

  /// spacing: 80
  static const double size20 = 80;

  /// spacing: 96
  static const double size24 = 96;

  /// spacing: 112
  static const double size28 = 112;

  /// spacing: 128
  static const double size32 = 128;

  /// spacing: 144
  static const double size36 = 144;

  /// spacing: 160
  static const double size40 = 160;

  /// spacing: 176
  static const double size44 = 176;

  /// spacing: 192
  static const double size48 = 192;

  /// spacing: 208
  static const double size52 = 208;

  /// spacing: 224
  static const double size56 = 224;

  /// spacing: 240
  static const double size60 = 240;

  /// spacing: 256
  static const double size64 = 256;

  /// spacing: 288
  static const double size72 = 288;

  /// spacing: 320
  static const double size80 = 320;

  /// spacing: 384
  static const double size96 = 384;

  /// spacing: 1
  static const double px = 1;

  /// spacing: 2
  static const double size0Point5 = 2;

  /// spacing: 6
  static const double size1Point5 = 6;

  /// spacing: 10
  static const double size2Point5 = 10;

  /// spacing: 14
  static const double size3Point5 = 14;
}

class LineHeight {
  const LineHeight();

  /// line-height: 12
  static const double size3 = 12;

  /// line-height: 16
  static const double size4 = 16;

  /// line-height: 20
  static const double size5 = 20;

  /// line-height: 24
  static const double size6 = 24;

  /// line-height: 28
  static const double size7 = 28;

  /// line-height: 32
  static const double size8 = 32;

  /// line-height: 36
  static const double size9 = 36;

  /// line-height: 40
  static const double size10 = 40;

  /// line-height: 1
  static const double none = 1;

  /// line-height: 1.25
  static const double tight = 1.25;

  /// line-height: 1.375
  static const double snug = 1.375;

  /// line-height: 1.5
  static const double normal = 1.5;

  /// line-height: 1.625
  static const double relaxed = 1.625;

  /// line-height: 2
  static const double loose = 2;
}

class LetterSpacing {
  const LetterSpacing();

  /// letter-spacing: -0.8
  static const double tighter = -0.8;

  /// letter-spacing: -0.4
  static const double tight = -0.4;

  /// letter-spacing: 0
  static const double normal = 0;

  /// letter-spacing: 0.4
  static const double wide = 0.4;

  /// letter-spacing: 0.8
  static const double wider = 0.8;

  /// letter-spacing: 1.6
  static const double widest = 1.6;
}

class BorderRadius {
  const BorderRadius();

  /// border-radius: 0
  static const double none = 0;

  /// border-radius: 2
  static const double sm = 2;

  /// border-radius: 4
  static const double sizeDefault = 4;

  /// border-radius: 6
  static const double md = 6;

  /// border-radius: 8
  static const double lg = 8;

  /// border-radius: 12
  static const double xl = 12;

  /// border-radius: 16
  static const double size2xl = 16;

  /// border-radius: 24
  static const double size3xl = 24;

  /// border-radius: 9999
  static const double full = 9999;
}

class BorderWidth {
  const BorderWidth();

  /// border-width: 0
  static const double size0 = 0;

  /// border-width: 2
  static const double size2 = 2;

  /// border-width: 4
  static const double size4 = 4;

  /// border-width: 8
  static const double size8 = 8;

  /// border-width: 1
  static const double sizeDefault = 1;
}
