import { camelCase, pascalCase } from "scule";
import resolveTwConfig from "tailwindcss/resolveConfig.js";
import path from "pathe";
import { loadConfig } from "c12";

interface CodegenContext {
    instancePath: string;
    classPrefix: string;
    remValue: number;
}

interface CodegenOptions {
    /**
     * default is 16
     */
    remValue?: number;
    classPrefix?: string;
}

export type TailwindConfigResult =
    | { success: false; data: null }
    | { success: true; data: ReturnType<typeof resolveTwConfig> };

export async function getResolvedTailwindConfig(
    configPath: string,
): Promise<TailwindConfigResult> {
    const resolvedPath = path.resolve(configPath);
    const { config } = await loadConfig({
        configFile: resolvedPath,
    });
    if (config === null) {
        return {
            success: false,
            data: null,
        };
    }
    const resolvedConfig = resolveTwConfig(config as any);
    return {
        success: true,
        data: resolvedConfig,
    };
}

export function tailwindConfigToDartString(
    config: ReturnType<typeof resolveTwConfig>,
    options: CodegenOptions = {},
): string {
    const startingContext: CodegenContext = {
        instancePath: "",
        classPrefix: options.classPrefix ?? "",
        remValue: options.remValue ?? 16,
    };
    const parts = [
        "// this file was autogenerated by tailwind-to-dart",
        "// see https://github.com/joshmossas/tailwind-to-dart for details",
        'import "dart:ui";',
        "",
        tailwindColorObjectToDartClass(
            config.theme.colors as unknown as TwValueObject,
            startingContext,
        ).content,
        "",
        tailwindFontSizeObjectToDartClass(
            config.theme.fontSize,
            startingContext,
        ).content,
        "",
        tailwindSpacingObjectToDartClass(
            config.theme.spacing as unknown as TwValueObject,
            startingContext,
        ).content,
    ];
    return parts.join("\n");
}

type TwValueObject = Record<string, Record<string, any> | string>;

export function tailwindColorObjectToDartClass(
    input: TwValueObject,
    context: CodegenContext,
): { className: string; content: string } {
    const isRoot = context.instancePath.length === 0;
    const className = !isRoot
        ? `_${pascalCase(context.instancePath.split("/").join("_"), { normalize: true })}`
        : `${context.classPrefix}Colors`;
    const colorParts: string[] = [];
    const colorSubParts: string[] = [];
    for (const [key, val] of Object.entries(input)) {
        if (typeof val === "string" && val.startsWith("#")) {
            colorParts.push(`/// ${val}`);
            const fieldPrefix = isRoot ? `static const` : `final`;
            colorParts.push(
                `${fieldPrefix} ${dartSafeKey(key, "shade")} = Color(0xFF${val.toUpperCase().replace("#", "")});`,
            );
            continue;
        }
        if (typeof val === "object") {
            const result = tailwindColorObjectToDartClass(
                val as TwValueObject,
                {
                    classPrefix: context.classPrefix,
                    instancePath:
                        context.instancePath.length > 0
                            ? `${context.instancePath}/${key}`
                            : `${className}/${key}`,
                    remValue: context.remValue,
                },
            );
            const fieldPrefix = isRoot ? `static ` : "";
            colorParts.push(
                `${fieldPrefix}${result.className} get ${dartSafeKey(key, "shade")} => ${result.className}();`,
            );
            colorSubParts.push(result.content);
            continue;
        }
    }
    const content = [`class ${className} {`, `  ${className}();`];
    for (const part of colorParts) {
        content.push(`  ${part}`);
    }
    content.push("}");
    for (const part of colorSubParts) {
        content.push("");
        content.push(part);
    }
    return {
        className,
        content: content.join("\n"),
    };
}

export const illegalChars = "0123456789";

export function tailwindFontSizeObjectToDartClass(
    input: TwValueObject,
    context: CodegenContext,
): { className: string; content: string } {
    const isRoot = context.instancePath.length === 0;
    const className = !isRoot
        ? `_${pascalCase(context.instancePath.split("/").join("_"), { normalize: true })}`
        : `${context.classPrefix}FontSizes`;
    const parts: string[] = [];
    const subParts: string[] = [];
    for (const [key, value] of Object.entries(input)) {
        if (typeof value === "string") {
            let pxValue = 0;
            if (value.includes("rem")) {
                pxValue = Number(value.replace("rem", "")) * context.remValue;
            } else if (value.includes("em")) {
                pxValue = Number(value.replace("em", "")) * context.remValue;
            } else if (value.includes("px")) {
                pxValue = Number(value.replace("px", ""));
            }
            const fieldPrefix = isRoot ? `static const` : `final`;
            parts.push(`/// fontSize: ${pxValue}px`);
            parts.push(
                `${fieldPrefix} double ${dartSafeKey(key, "size")} = ${pxValue};`,
            );
            continue;
        }
        if (typeof value === "object") {
            const result = tailwindFontSizeObjectToDartClass(
                value as TwValueObject,
                {
                    instancePath:
                        context.instancePath.length > 0
                            ? `${context.instancePath}/${key}`
                            : `${className}/${key}`,
                    remValue: context.remValue,
                    classPrefix: context.classPrefix,
                },
            );
            const fieldPrefix = isRoot ? `static ` : ``;
            parts.push(
                `${fieldPrefix}${result.className} get ${dartSafeKey(key, "size")} => ${result.className}();`,
            );
            subParts.push(result.content);
        }
    }
    const content = [`class ${className} {`, `  ${className}();`];
    for (const part of parts) {
        content.push(`  ${part}`);
    }
    content.push("}");
    for (const part of subParts) {
        content.push("");
        content.push(part);
    }
    return {
        className,
        content: content.join("\n"),
    };
}

export function tailwindSpacingObjectToDartClass(
    input: TwValueObject,
    context: CodegenContext,
): { className: string; content: string } {
    const isRoot = context.instancePath.length === 0;
    const className = !isRoot
        ? `_${pascalCase(context.instancePath.split("/").join("_"), { normalize: true })}`
        : `${context.classPrefix}Space`;
    const parts: string[] = [];
    const subParts: string[] = [];
    for (const [key, val] of Object.entries(input)) {
        if (typeof val === "string") {
            let pxValue = 0;
            if (val.includes("rem")) {
                pxValue = Number(val.replace("rem", "")) * context.remValue;
            } else if (val.includes("em")) {
                pxValue = Number(val.replace("em", "")) * context.remValue;
            } else if (val.includes("px")) {
                pxValue = Number(val.replace("px", ""));
            } else {
                console.warn(
                    `Unable to convert spacing value {"${key}": "${val}"}`,
                );
                continue;
            }
            const fieldPrefix = isRoot ? `static const` : `final`;
            parts.push(`/// size: ${pxValue}px`);
            parts.push(
                `${fieldPrefix} double ${dartSafeKey(key, "size")} = ${pxValue};`,
            );
            continue;
        }
        if (typeof val === "object") {
            const result = tailwindSpacingObjectToDartClass(
                val as TwValueObject,
                {
                    classPrefix: context.classPrefix,
                    remValue: context.remValue,
                    instancePath:
                        context.instancePath.length > 0
                            ? `${context.instancePath}/${key}`
                            : `${className}/${key}`,
                },
            );
            const fieldPrefix = isRoot ? `static ` : ``;
            parts.push(
                `${fieldPrefix}${result.className} get ${dartSafeKey(key, "size")} => ${result.className}();`,
            );
            subParts.push(result.content);
        }
    }
    const content = [`class ${className} {`, `  ${className}();`];
    for (const part of parts) {
        content.push(`  ${part}`);
    }
    content.push(`}`);
    for (const part of subParts) {
        content.push("");
        content.push(part);
    }
    return {
        className,
        content: content.join("\n"),
    };
}

function dartSafeKey(key: string, fallbackPrefix: string): string {
    let finalKey = key;
    if (finalKey.includes(".")) {
        finalKey = finalKey.replaceAll(".", "_point_");
    }
    for (const char of illegalChars) {
        if (finalKey.startsWith(char)) {
            finalKey = `${fallbackPrefix}_${finalKey}`;
        }
    }

    return camelCase(finalKey, {
        normalize: true,
    });
}
